export const FILTERED_HISTORY_REQUEST = 'FILTERED_HISTORY_REQUEST';
export const FILTERED_HISTORY_REQUEST_FAILURE = 'FILTERED_HISTORY_REQUEST_FAILURE';
export const FILTERED_HISTORY_REQUEST_SUCCESS = 'FILTERED_HISTORY_REQUEST_SUCCESS';