export const ROLE_CHANGE = 'ROLE_CHANGE';
export const ROLE_CHANGE_SUCCESS = 'ROLE_CHANGE_SUCCESS';
export const ROLE_CHANGE_FAILURE = 'ROLE_CHANGE_FAILURE';
export const ROLE_FETCH = 'ROLE_FETCH';
export const ROLE_FETCH_SUCCESS = 'ROLE_FETCH_SUCCESS';
export const ROLE_FETCH_FAILURE = 'ROLE_FETCH_FAILURE';
