import { Status } from 'Models/Status';

export const ACCOUNT_INFORMATION_SAVE = 'ACCOUNT_INFORMATION_SAVE';
export const ACCOUNT_INFORMATION_SAVE_SUCCESS = 'ACCOUNT_INFORMATION_SAVE_SUCCESS';
export const ACCOUNT_INFORMATION_STATUS = 'ACCOUNT_INFORMATION_STATUS';
export const ACCOUNT_INFORMATION_GOOGLE_AUTHENTICATION_STATUS = 'ACCOUNT_INFORMATION_GOOGLE_AUTHENTICATION_STATUS';
export const ACCOUNT_INFORMATION_GOOGLE_AUTHENTICATION = 'ACCOUNT_INFORMATION_GOOGLE_AUTHENTICATION';
export const ACCOUNT_INFORMATION_TWO_FACTOR_STATUS = 'ACCOUNT_INFORMATION_TWO_FACTOR_STATUS';
export const ACCOUNT_INFORMATION_TWO_FACTOR_ENABLED = 'ACCOUNT_INFORMATION_TWO_FACTOR_ENABLED';

export type IState = {
  status: Status,
  googleAuthentication: {
    status: Status,
    data: object,
  },
  twoFactor: {
    status: Status,
    enabled_2fa: number,
  },
};
